#XXX GENERATED BY generate_schema.pl
package  TwitterPaste::DB::Schema;
use strict;
use warnings;


use Teng::Schema::Declare;
use Time::Piece::MySQL;
use JSON;

    table{
        name 'content';
        pk qw (
        id
        );
        columns qw(
            body
            created_at
            rid_hash
            rid
            id
        );
        inflate qr/_at$/ => sub {
            Time::Piece->from_mysql_datetime(shift);
        };
        deflate qr/_at$/ => sub {
            shift->mysql_datetime;
        };
        row_class 'TwitterPaste::Model::Content';
    };

1;
